version: "3"
 
services:
  dash-sample-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: dash-sample-app
    container_name: dash-sample-app
    ports: 
       - "8050:8050"
    command: 
      [ "gunicorn", "--workers=1", "--threads=1", "-b 0.0.0.0:8050", "main:server"]
    networks:
       - network 

networks:
   network:
     driver: bridge